### ISSUE TITLE
Text of Relationships between Nodes overlap with each other

### ISSUE THREAD

**Issue by viveksacademia4git** [vivopensource/ng-neo4jd3#1]
If multiple relationships exist between the same Actor and Object, the name of relationships placed between the connecting arrow overlap with each other as shown in the diagram.

![image](https://user-images.githubusercontent.com/45398326/86125527-1a4cc900-badd-11ea-9d1b-718d437886e3.png)

**Comment by viveksacademia4git** [comment]
For now, merged the two cells

![image](https://user-images.githubusercontent.com/45398326/86127131-b4ae0c00-badf-11ea-8533-8fa494887d1d.png)

**Comment by BSandy35** [comment]
Hi @viveksacademia4git ,

Can you help me with something in this project.

Thanks,
Sandhya
